[nfs]
172.31.22.171 ansible_ssh_user='ec2-user'

[webservers]
172.31.19.2 ansible_ssh_user='ec2-user'
172.31.28.34 ansible_ssh_user='ec2-user'

[db]
172.31.20.70 ansible_ssh_user='ec2-user'

[lb]
172.31.25.168 ansible_ssh_user='ubuntu'